### PR TITLE
Integrate latest FBSDK on iOS and JS

### LINKED ISSUE #533: Use of undeclared identifier 'FBSDKLoginBehaviorNative'; did you mean 'FBSDKLoginBehaviorBrowser'?
## 🐛 Bug Report

Fresh install of the package... iOS build fails with:

Use of undeclared identifier 'FBSDKLoginBehaviorNative'; did you mean 'FBSDKLoginBehaviorBrowser'?
RCTFBSDKLoginButtonManager.m line 49

## To Reproduce
Follow iOS install instructions

## Expected Behavior
Successful build

## Environment
React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
      Memory: 236.19 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.1.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1 
      react-native: 0.56.0 => 0.56.0 
    npmGlobalPackages:
      react-native-cli: 2.0.1

### PR DESCRIPTION
**Pull request by redcancode**
There have been some breaking changes in the native FBSDK this year which prevents us from using the latest version. I've decided to help the problem and integrate the latest changes with this pull request.

Currently I've integrated the iOS FBSDK changes. My app builds and runs and I was able to login and obtain an access token. I'm not finished with these integrations.

Here are the list of things I want to do:

- double check iOS FBSDK changes to make sure I've got everything
- integrate Android FBSDK similarly
- document all the changes I've made
- test all the affected features

After I've done with these items this PR should be ready for a real review and consideration to merge it and support the latest FBSDK on both platforms.

It would be great if you could try this out and confirm that it works for you too. Everything should work on iOS.

I've started my branch from the latest published version which is `0.9.0`. I did this on purpose because `master` is broken currently due to `RCTComponentEvent` still being unpublished.

Your feedback would be greatly appreciated. 🙂

**[Update-2019-June-14]** This PR has been repurposed into integrating the latest FBSDK on iOS and JS only. The android part has been done in PR #546 

Fixes #533

### CODE REVIEW

**Comment by simonbengtsson** [comment]
Awesome! Will test it with other iOS app before the end of the day.

**Comment by simonbengtsson** [comment]
I ran into build issues when trying. At first it was a bolt thing which got resolved after `pod deintegrate && pod install`. Then it was an issue about `'React/RCTComponentEvent.h' file not found`. Got the same when running the official master branch though (https://github.com/facebook/react-native-fbsdk/issues/493). You didn't run into this?

**Comment by redcancode** [comment]
My branch doesn’t have code that depend on `RCTComponentEvent`. I think you
aren’t building my branch directly. 🙂

I did ran into this issue on the `master` branch. Someone accidentally
merged a feature that was waiting for `RCTComponentEvent` to be released.
That is why it doesn’t build and that is why I based my changes off of
`0.9.0` because that tag doesn’t depend on that unreleased feature.

Maybe you merged my branch locally and tried to build that way? In that
case it would fail with the error you mentioned. My branch alone shouldn’t
fail with that error.

**Comment by simonbengtsson** [comment]
You are right!. My mistake was specifying `github:redcancode/react-native-fbsdk` instead of `github:redcancode/react-native-fbsdk#integrate-latest-fbsdk` in package.json.

Getting passed that, I get other compile issues though.

Screenshot 2019-06-13 at 00 21 35

**Comment by simonbengtsson** [comment]
You are right! My mistake was specifying `github:redcancode/react-native-fbsdk` instead of `github:redcancode/react-native-fbsdk#integrate-latest-fbsdk`. Everything seems to be working in our project.

**Comment by redcancode** [comment]
Those must be valid errors. I haven’t integrated the changes in ShareKit, I
was hoping it would just work. I will write a comment here when I’ve done
that too. 🤓

Thanks for checking.

**Comment by simonbengtsson** [comment]
Was a bit quick in posting that comment, wrote on updated comment above. The issues mentioned went away after first fixing compile issues from upgrading to v5 of the native sdk in our native app before upgrading react-native-fbsdk.

**Comment by redcancode** [comment]
Those are valid errors. If you pull in the `Share` subspec of `react-native-fbsdk` you will get those build errors because there were changes in `FBSDKShareKit` too. I'm already working on fixing them.

**Comment by janicduplessis** [comment]
@redcancode Thanks a lot for working on this! I'm just updated the example app in the repo to target RN 0.60 which fixes the `RCTComponentEvent` error. My goal here is to publish a new version that targets RN 0.60+ and fbsdk@5+.

Sadly it won't be backwards compatible but users are free to stay on an older version until RN can be updated.

If you are okay with that I can merge this PR as is and work on fixing the remaining errors in `FBSDKShareKit`

**Comment by redcancode** [comment]
@janicduplessis I'm not ready with this PR yet. I've made progress with the integration of `ShareKit` on iOS, might be pretty close to being done with it.

I think it would be a great idea to create a new branch for this effort called something like `integrate-fbsdk-v5` we could build that branch together and only merge to `master` when everything is ready on iOS and Android.

What do you say? 🙂

**Comment by janicduplessis** [comment]
@redcancode `master` has been in pretty bad shape for a while so we can just work there directly to get it back in good shape ASAP.

I think a good way to split this work is you can make the required changes for iOS / JS and I'll take care of android.

File: ios/RCTFBSDK/login/RCTConvert+FBSDKLogin.m [hunk 1]
```diff
@@ -21,11 +21,8 @@
 @implementation RCTConvert(FBSDKLogin)
 
 RCT_ENUM_CONVERTER(FBSDKLoginBehavior, (@{
```
Comment (janicduplessis) [inline ios/RCTFBSDK/login/RCTConvert+FBSDKLogin.m]: I think we should just remove login behavior completely since it only has one value now.

**Comment by janicduplessis** [comment]
Also if you want to make testing easier you can try the new example app, the instructions to run it are [here](https://github.com/facebook/react-native-fbsdk#example-app)

**Comment by redcancode** [comment]
@janicduplessis Okay let's use `master` then and fix it up. In this case I will change this PR so it will be about integrating `CoreKit` and `LoginKit` on iOS and JS. That way you can merge it and we can iterate faster.

I will create another PR about `ShareKit` later which could include other improvements you notice on the way, like the one you commented above.

File: ios/RCTFBSDK/login/RCTConvert+FBSDKLogin.m (hunk 1 above)
Comment (janicduplessis) [reply ios/RCTFBSDK/login/RCTConvert+FBSDKLogin.m]: Actually nevermind, let's keep the prop since it is still used for Android

File: ios/RCTFBSDK/login/RCTFBSDKLoginManager.m [hunk 2]
```diff
@@ -104,14 +103,8 @@ - (void)_loginWithPermissions:(NSStringArray *)permissions
...
-#pragma clang diagnostic push
-#pragma clang diagnostic ignored "-Wdeprecated-declarations"
-  if (isRead) {
-    [_loginManager logInWithReadPermissions:permissions handler:requestHandler];
-  } else {
-    [_loginManager logInWithPublishPermissions:permissions handler:requestHandler];
-  }
-#pragma clang diagnostic pop
+
+  [_loginManager logInWithPermissions:permissions fromViewController:nil handler:requestHandler];
```
Comment (redcancode) [inline ios/RCTFBSDK/login/RCTFBSDKLoginManager.m]: @janicduplessis does this works the same way on android too? because if it does we should remove the double methods on js side. right now we have `loginWithReadPermissions` and `loginWithPublishPermissions` on js side, but on iOS it runs into a single `loginWithPermissions` method.

**Comment by redcancode** [comment]
@janicduplessis i've finished with all the changes. also updated the original PR description. the only problem is that i can't build the example app because of some pods path issue. i will solve that later this week. i was able to build my app with these changes though

File: ios/RCTFBSDK/login/RCTFBSDKLoginManager.m (hunk 2 above)
Comment (janicduplessis) [reply ios/RCTFBSDK/login/RCTFBSDKLoginManager.m]: I did a bit of research and on Android the 2 different methods are not deprecated but do end up calling the same `logIn` method.

I think we could change the js api to have a single `logIn` method and deprecate the 2 other ones.

File: ios/RCTFBSDK/share/RCTConvert+FBSDKSharingContent.m [hunk 3]
```diff
@@ -112,10 +112,6 @@ static void RCTAppendGenericContent(RCTFBSDKSharingContent contentObject, NSDict
   NSURL *videoURL = [RCTConvert NSURL:videoData[@"localUrl"]];
   FBSDKShareVideo *video = [FBSDKShareVideo videoWithVideoURL:videoURL];
   videoContent.video = video;
-  if (contentData[@"previewPhoto"]) {
```
Comment (janicduplessis) [inline ios/RCTFBSDK/share/RCTConvert+FBSDKSharingContent.m]: `previewPhoto` still exists but is on `video` now.

Something like:
`videoContent.video. previewPhoto = previewPhoto`

File: ios/RCTFBSDK/share/RCTConvert+FBSDKSharingContent.m [hunk 4]
```diff
@@ -132,15 +128,16 @@ static void RCTAppendGenericContent(RCTFBSDKSharingContent contentObject, NSDict
 static FBSDKShareOpenGraphAction *RCTBuildOpenGraphAction(NSDictionary *actionData)
 {
   FBSDKShareOpenGraphAction *action = nil;
+  NSString *actionType = nil;
```
Comment (janicduplessis) [inline ios/RCTFBSDK/share/RCTConvert+FBSDKSharingContent.m]: I don't think we need to declare this variable here, could just be `NSString *actionType = [RCTConvert...` on line 133

**Comment by janicduplessis** [comment]
Actually lets just merge this and you can address the feedback in a followup. I'll work on updating the login method to have a single one instead of loginWithReadPermissions and loginWithPublishPermissions.

File: ios/RCTFBSDK/login/RCTFBSDKLoginManager.m (hunk 2 above)
Comment (redcancode) [reply ios/RCTFBSDK/login/RCTFBSDKLoginManager.m]: sounds perfect. i see you already did something similar 👍

File: ios/RCTFBSDK/share/RCTConvert+FBSDKSharingContent.m (hunk 3 above)
Comment (redcancode) [reply ios/RCTFBSDK/share/RCTConvert+FBSDKSharingContent.m]: nice find. i will create a pr to add it back the correct way.

File: ios/RCTFBSDK/share/RCTConvert+FBSDKSharingContent.m (hunk 4 above)
Comment (redcancode) [reply ios/RCTFBSDK/share/RCTConvert+FBSDKSharingContent.m]: okay. i will improve this in the preview photo pr :)
